### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by FaceTheDream** [goKarts/ShiftersCanada#16]
- [ ] Get Scroll-spy working
- [ ] Clean PHP up. (Use AJAX and jQuery where we can)
- [ ] Properly display error messages, without page refresh.
    - [ ] Use Bootstrap Alerts.
